name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2511ma!
          POSTGRES_DB: trustlayer_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest psycopg2

  - name: Restore database from dump
    run: |
      pg_restore --no-owner --no-privileges --clean --if-exists \
        --host=127.0.0.1 --port=5432 --username=postgres \
        --dbname=trustlayer_test trustlayer_dump.sql
    env:
      PGPASSWORD: 2511ma!

      - name: Run tests
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: 2511ma!
          PGDATABASE: trustlayer_test
        run: pytest -v